### ISSUE TITLE
Pulling API data into the conversation

### ISSUE THREAD

**Issue by ruscles** [arleyandrada/MessagesIOS#2]
I am working with the default example and I am trying to pull live data from an API instead of the fake conversation. What is the best way to replace the dummy data with another data source?

My data being passed is being passed in from another controller based on the ArrayIndex.

```
(
           {
           date = 1459353383000;
           message = "Test description 1";
           sender = "--";
       },
           {
           date = 1459353383000;
           message = "Test description 2";
           sender = "--";
       }
 )
```

Thanks!

**Comment by arleyandrada** [comment]
Rewrite the data.js file (fake datasource) and keep the same methods, with same parameters and same JSON response format.
